### ISSUE TITLE
Possible deployment error

### ISSUE THREAD

**Issue by davidsowerby** [davidmigloz/langchain_dart#13]
I installed the library from pub.dev: langchain: ^0.0.1-dev.1

I am getting a compile error, with **call** (and generate) not recognised as methods within the second line of:

```dart
  final OpenAI llm = OpenAI(apiKey: openaiApiKey, temperature: 0.9);
  print(await llm.call(prompt: 'x'));
  ```
  
  I drilled through to langchain.dart, which contains only:

```dart
library  

  export 'src/langchain_base.dart';
```

which in turn contains only:

```dart
class LangChain {
  bool get isAwesome => true;
}
```

The code I cloned from the 'main' branch, langchain.dart contains:

```dart
/// Build powerful LLM-based Dart/Flutter applications.
library;

export 'src/llms/base.dart';
export 'src/schema.dart';
```

and src/langchain_base.dart' contains code for BaseLLM etc.

Seems like what was deployed to pub.dev is behind the repository code

**Comment by davidsowerby** [comment]
Just realised, you are operating just the main branch at this stage.  So it may just need a +2 release

**Comment by davidmigloz** [comment]
Indeed, I just published the package in pub.dev to claim the name, but the current version is way behind master. 
Maybe in the future, we can deploy nightly dev builds automatically. But for now, I would suggest you use master:

```yaml
dependencies:
  langchain: ^0.0.1-dev.1
  langchain_openai: ^0.0.1-dev.1

dependency_overrides:
  langchain:
    git:
      url: https://github.com/davidmigloz/langchain_dart
      path: packages/langchain/
      branch: master
  langchain_openai:
    git:
      url: https://github.com/davidmigloz/langchain_dart
      path: packages/langchain_openai/
      branch: master
```
