### ISSUE TITLE
Support FastChat OpenAI-compatible API

### ISSUE THREAD

**Issue by guchengxi1994** [davidmigloz/langchain_dart#442]
### Feature request

While deploying a model locally and using FastChat, I encountered an exception when attempting to fetch results via stream.
![image](https://github.com/davidmigloz/langchain_dart/assets/33513462/bd2a2061-fa56-451d-8f5b-1266f58c27f0)
![image](https://github.com/davidmigloz/langchain_dart/assets/33513462/15dd4020-3254-49bf-a1d9-371ca44bc0ba)

It appears that FastChat is not providing a created value. As I'm not fully familiar with the OpenAI API, could the created attribute be nullable?

### Motivation

make `create` nullable and support fastchat

### Your contribution

null

**Comment by davidmigloz** [comment]
hey @guchengxi1994,

Thanks for reporting it, I'll make that field nullable. Was that the only problematic field?

**Comment by guchengxi1994** [comment]
I have reviewed the source code of FastChat as well as recent pull requests, and found that this issue is likely related to the implementation of FastChat. However, FastChat has not released a new version for some time (over 3 months). I believe it would be better to make both the created and object parameters nullable.
I apologize for raising this issue abruptly; it might be more appropriate as a suggestion.

**Comment by davidmigloz** [comment]
Thanks for the info, I've made `created` and `object` fields nullable in https://github.com/davidmigloz/langchain_dart/pull/444. I will release a new version this week. For now you can fetch the package from git:

```yaml
  openai_dart:
    git:
      url: https://github.com/davidmigloz/langchain_dart.git
      path: packages/openai_dart
      ref: ddaf1f69d8262210637999367690bf362f2dc5c3
```
